spring:
  application:
    name: rotaunica
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  web:
    error:
      include-binding-errors: always
      include-message: always

server:
  port: 8080

logging:
  level:
    '[com.viagens.rotaunica]': DEBUG